# Generated by Django 2.0.5 on 2018-05-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='slug'),
        ),
    ]
