# Generated by Django 2.0.5 on 2018-05-24 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0002_auto_20180524_0937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-updated_at', '-created_at'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
    ]
