# Generated by Django 2.0.5 on 2018-05-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0004_article_featured_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='...', verbose_name='description'),
            preserve_default=False,
        ),
    ]
